_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: fr
uuid: 988b6014-1bff-4f46-b7b7-7b3571d5daa7
name: ActenBlog
mail: admin@actency.fr
slogan: "L'actualité Drupal à la sauce actenciennes"
page:
  403: ''
  404: ''
  front: /
admin_compact_mode: false
weight_select_max: 100
default_langcode: fr
